let $DESKTOP   = '~/Desktop'
let $BUNDLE    = '~/Dropbox/vim/bundle'
let $NEOBUNDLE = '~/Dropbox/vim/bundle/neobundle.vim'
let $LOCALWORK = '~/Dropbox/vim/local'       " <- 各PC毎に設定するフォルダ
let $VIMWORK   = '~/Dropbox/vim/vimwork'     " <- このファイルを指定してください
let $VIMTMP    = '~/vim'

" = plugin =
if 1 " perforce use
set rtp+=~/Dropbox/vim/rtp/unite-perforce.vim " <- provide thier own
call perforce#init()
endif 

" = map =
nnoremap ;dv<CR> :e ~/Dropbox/vim/vimwork/vimrc.vim<CR>

" = unite =
let g:atmark_jump_is_unite = 1

 "= source =
so ~/Dropbox/vim/vimwork/neobundle.vim
so ~/Dropbox/vim/vimwork/vimrc.vim

" = flg =
let g:atmark_jump_is_unite = 1
